---
label: Project
hide_body: true
fields:
- type: list
  name: tags
  label: tags
- type: text
  name: title
  label: title
- type: datetime
  name: date
  label: date
- type: file
  name: image
  label: image
- type: text
  name: caption
  label: caption
- type: text
  name: excerpt
  label: excerpt
- type: text
  name: code
  label: code
- type: text
  name: external_link
  label: external_link
- type: text
  name: external_link_name
  label: external_link_name
- type: text
  name: read_more_bypass
  label: read_more_bypass
pages:
- pages/the-mom-test.md
- projects/smart-lock.md
